api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  collection:
    pagination:
      items_per_page: 2
      client_enabled: true
      enabled_parameter_name: pagination

  http_cache:
    invalidation:
      enabled: true
      varnish_urls: []
    max_age: 3600
    shared_max_age: 3600
    vary: ["Content-Type", "Authorization", "Origin"]
    public: true
