nelmio_cors:
  paths:
    "^/":
      allow_origin: ["http://127.0.0.1:5500"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
      allow_headers: ["Accept", "Content-Type", "Authorization"]
      max_age: 3600
    debug: true
